name: Release
on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Dependencies And Build
        run: |
          yarn install
          yarn run build

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.bobplugin"
          token: ${{ secrets.GIT_TOKEN }}